italianTopics = {
    "easter": "pasqua",
    "disabilities": "disabilità",
    "comics": "fumetti",
    "change": "cambiamenti",
    "chores": "faccende domestiche",
    "airplanes": "aereo",
    "cheating": "imbrogli",
    "clothes": "vestiti",
    "creativity": "creatività",
    "drugs": "droghe",
    "art": "arte",
    "celebrities": "celebrità",
    "death": "morte",
    "childhood": "infanzia",
    "education": "educazione",
    "entertainment": "intrattenimento",
    "business": "business",
    "body_language": "linguaggio del corpo",
    "adoption": "adozioni",
    "birthdays": "compleanni",
    "advice": "consigli",
    "conflict": "conflitti",
    "diet": "diete",
    "books": "libri",
    "basketball": "pallacanestro",
    "complaining": "lamentarsi",
    "beauty": "bellezza",
    "arguing": "litigi",
    "facebook": "facebook",
    "wishes": "desideri",
    "cities": "città",
    "colors": "colori",
    "animals": "animali",
    "disaster": "disastri",
    "corruption": "corruzione",
    "cars": "automobili",
    "advertising": "pubblicità",
    "environment": "ambiente",
    "beach": "spiaggia",
    "dreams": "sogni",
    "behaviour": "comportamento",
    "countries": "paesi",
    "crime": "criminalità",
    "bags": "borse",
    "dating": "appuntamenti",
    "community": "comunità",
    "children": "bambini",
    "charity": "beneficienza",
    "earthquakes": "terremoti",
    "university": "università",
    "culture": "culture",
    "dangers": "pericoli",
    "conversation": "conversazioni",
    "aging": "invecchiare"
}


englishTopics = {
    "all": "all",
    "computers": "computers",
    "easter": "easter",
    "disabilities": "disabilities",
    "comics": "comics",
    "change": "change",
    "chores": "chores",
    "airplanes": "airplanes",
    "university": "university",
    "cheating": "cheating",
    "clothes": "clothes",
    "creativity": "creativity",
    "drugs": "drugs",
    "art": "art",
    "celebrities": "celebrities",
    "death": "death",
    "childhood": "childhood",
    "education": "education",
    "entertainment": "entertainment",
    "business": "business",
    "body_language": "body language",
    "adoption": "adoption",
    "birthdays": "birthdays",
    "advice": "advice",
    "conflict": "conflict",
    "diet": "diet",
    "books": "books",
    "basketball": "basketball",
    "complaining": "complaining",
    "beauty": "beauty",
    "arguing": "arguing",
    "facebook": "facebook",
    "wishes": "wishes",
    "cities": "cities",
    "colors": "colors",
    "animals": "animals",
    "disaster": "disaster",
    "corruption": "corruption",
    "cars": "cars",
    "advertising": "advertising",
    "environment": "environment",
    "beach": "beach",
    "dreams": "dreams",
    "behaviour": "behaviour",
    "countries": "countries",
    "crime": "crime",
    "pets": "pets",
    "bags": "bags",
    "dating": "dating",
    "community": "community",
    "children": "children",
    "charity": "charity",
    "earthquakes": "earthquakes",
    "culture": "culture",
    "dangers": "dangers",
    "conversation": "conversation",
    "aging": "aging",
}


frenchTopics = {
    "all": "all",
    "computers": "ordinateurs",
    "easter": "pâques",
    "disabilities": "handicaps",
    "comics": "comics",
    "change": "changer",
    "chores": "corvées",
    "airplanes": "avions",
    "university": "université",
    "cheating": "tricherie",
    "clothes": "vêtements",
    "creativity": "créativité",
    "drugs": "drogues",
    "art": "art",
    "celebrities": "célébrités",
    "death": "mort",
    "childhood": "enfance",
    "education": "éducation",
    "entertainment": "divertissement",
    "business": "entreprise",
    "body_language": "langage corporel",
    "adoption": "adoption",
    "birthdays": "anniversaires",
    "advice": "conseil",
    "conflict": "conflit",
    "diet": "régime",
    "books": "livres",
    "basketball": "basketball",
    "complaining": "se plaindre",
    "beauty": "beauté",
    "arguing": "argumenter",
    "facebook": "facebook",
    "wishes": "souhaite",
    "cities": "villes",
    "colors": "couleurs",
    "animals": "animaux",
    "disaster": "catastrophe",
    "corruption": "corruption",
    "cars": "voitures",
    "advertising": "publicité",
    "environment": "environment",
    "beach": "plage",
    "dreams": "rêves",
    "behaviour": "comportement",
    "countries": "pays",
    "crime": "crime",
    "pets": "pets",
    "bags": "sacs",
    "dating": "dating",
    "community": "communauté",
    "children": "enfants",
    "charity": "charity",
    "earthquakes": "tremblements de terre",
    "culture": "culture",
    "dangers": "dangers",
    "conversation": "conversation",
    "aging": "vieillissement",
}

spanishTopics = {
    "all": "todos",
    "computers": "computadores",
    "easter": "pascua",
    "disabilities": "discapacidades",
    "comics": "comics",
    "change": "cambiamento",
    "chores": "deberes",
    "airplanes": "aeroplanos",
    "university": "universidad",
    "cheating": "trampa",
    "clothes": "ropa",
    "creativity": "creatividad",
    "drugs": "drogas",
    "art": "arte",
    "celebrities": "celebridades",
    "death": "muerte",
    "childhood": "infancia",
    "education": "Educación",
    "entertainment": "entretenimiento",
    "business": "business",
    "body_language": "lenguaje corporal",
    "adoption": "adopción",
    "birthdays": "cumpleaños",
    "advice": "consejos",
    "conflict": "conflictos",
    "diet": "dieta",
    "books": "libros",
    "basketball": "basketball",
    "complaining": "quejárse",
    "beauty": "belleza",
    "arguing": "discutir",
    "facebook": "facebook",
    "wishes": "deseos",
    "cities": "ciudades",
    "colors": "colores",
    "animals": "animales",
    "disaster": "desastres",
    "corruption": "corrupción",
    "cars": "coches",
    "advertising": "publicidad",
    "environment": "entorno",
    "beach": "playa",
    "dreams": "sueños",
    "behaviour": "comportamiento",
    "countries": "países",
    "crime": "crimen",
    "pets": "pets",
    "bags": "bolsas",
    "dating": "citas",
    "community": "comunidad",
    "children": "niños",
    "charity": "caridad",
    "earthquakes": "terremotos",
    "culture": "culturas",
    "dangers": "peligros",
    "conversation": "conversación",
    "aging": "vejez",
}

italianCategories = {
    "all": 'tutte',
    "languages": 'Lingue',
    "friends": 'Amici',
    "school": 'Scuola',
    "work": 'Lavoro',
    "relax": 'Relax',
    "fun": 'Divertimento',
    "romance": 'Amore',
}


englishCategories = {
    "all": 'all',
    "languages": 'languages',
    "friends": 'friends',
    "school": 'school',
    "work": 'work',
    "relax": 'relax',
    "fun": 'fun',
    "romance": 'romance',
}


frenchCategories = {
    "all": 'tous',
    "languages": 'langues',
    "friends": 'amis',
    "school": 'école',
    "work": 'travail',
    "relax": 'relax',
    "fun": 'fun',
    "romance": 'romance',
}

spanishCategories = {
    "all": 'todos',
    "languages": 'idiomas',
    "friends": 'amigos',
    "school": 'escuela',
    "work": 'trabajo',
    "relax": 'relax',
    "fun": 'divertimiento',
    "romance": 'romance',
}


def get_topic(word, lang):
    if lang == "it":
        return italianTopics[word] if word in italianTopics else False
    if lang == "fr":
        return frenchTopics[word] if word in frenchTopics else False
    if lang == "es":
        return spanishTopics[word] if word in spanishTopics else False
    else:
        return englishTopics[word] if word in englishTopics else False


def get_category(word, lang):
    if lang == "it":
        return italianCategories[word] if word in italianCategories else False
    if lang == "fr":
        return frenchCategories[word] if word in frenchCategories else False
    if lang == "es":
        return spanishCategories[word] if word in spanishCategories else False
    else:
        return englishCategories[word] if word in englishCategories else False


HASH_DIGITS = 8


def get_hash(string1, string2="*"):
    return (hash(string1+"*"+string2)) % (10 ** HASH_DIGITS)
