export default {
  CARDS_THEME: '@cards_theme',
  FONTSIZE: '@fontsize',
  LANGUAGE_KEY: '@lang',
  RECENT_SEARCH_KEY: '@recent_search',
  THEME_KEY: '@theme',
  LAST_UPDATE_KEY: '@last_update',
  HAS_LAUNCHED: '@launched',
  FIRST_UPDATED: '@first_updated',
  IS_UPDATED: '@is_updated',
  CURRENT_DB: '@current_db',
  SETTINGS_UPDATE: '@settings_update',
  USER_CATEGORIES_ID: '@user_categories_id',
  USER_LEVEL: '@user_level',
  USER_GOALS: '@user_goals',
  USED_LANGUAGES: '@used_languages',
  TOPICS_NUMBER: '@topic_number',
  FIRST_HELP: '@first_help',
  USER_LAST_TIMESTAMP: '@user_last_timestamp',
  USER_SYNCED: '@user_synced',
};
