require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'MyApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'
  
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
  
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
   post_install do |installer|
     flipper_post_install(installer)
   end
  
  target 'MyAppTests' do
    inherit! :complete
    # Pods for testing
  end
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' }) # update this part
  # post_install do |installer|
  #  flipper_post_install(installer)
  # end
end


target 'MyApp-tvOS' do
  # Pods for MyApp-tvOS

  target 'MyApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
